/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartSnippetsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var DEFAULT_SETTINGS = {
  triggerKey: "/",
  showSuggestions: true,
  snippets: [
    {
      trigger: "meeting",
      description: "Meeting notes template",
      template: `# Meeting Notes - {{date}}

**Attendees:** 
- 

**Agenda:**
1. 

**Discussion:**


**Action Items:**
- [ ] 

**Next Steps:**
`
    },
    {
      trigger: "todo",
      description: "Task list template",
      template: `## Tasks - {{date}}

- [ ] 
- [ ] 
- [ ] 

**Priority:**
\u{1F534} High: 
\u{1F7E1} Medium: 
\u{1F7E2} Low: `
    },
    {
      trigger: "idea",
      description: "Idea capture template",
      template: `\u{1F4A1} **Idea:** 

**Date:** {{date}}
**Time:** {{time}}

**Description:**


**Why this matters:**


**Next steps:**
- `
    },
    {
      trigger: "note",
      description: "Quick note template",
      template: `\u{1F4DD} {{date}} {{time}}

`
    },
    {
      trigger: "daily",
      description: "Daily log template",
      template: `# Daily Log - {{date}}

## \u{1F3AF} Goals for Today
- [ ] 
- [ ] 
- [ ] 

## \u{1F4DD} Notes


## \u2705 Completed
- 

## \u{1F4AD} Thoughts
`
    },
    {
      trigger: "project",
      description: "Project outline template",
      template: `# Project: 

**Status:** \u{1F7E1} In Progress
**Started:** {{date}}
**Deadline:** 

## Overview


## Goals
- 
- 
- 

## Tasks
- [ ] 
- [ ] 

## Resources
- 

## Notes
`
    },
    {
      trigger: "table",
      description: "Simple table",
      template: `| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
|          |          |          |
|          |          |          |`
    },
    {
      trigger: "code",
      description: "Code block",
      template: "```\n\n```"
    }
  ]
};
var SmartSnippetsPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerEditorExtension(this.createSnippetExtension());
    this.addCommand({
      id: "show-all-snippets",
      name: "Show all available snippets",
      callback: () => {
        this.showSnippetList();
      }
    });
    this.addSettingTab(new SmartSnippetsSettingTab(this.app, this));
    console.log("Smart Snippets plugin loaded");
  }
  onunload() {
    console.log("Smart Snippets plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  showSnippetList() {
    const snippetList = this.settings.snippets.map((s) => `${this.settings.triggerKey}${s.trigger} - ${s.description}`).join("\n");
    new import_obsidian.Notice(`Available Snippets:

${snippetList}`, 1e4);
  }
  expandSnippet(template) {
    const now = new Date();
    let expanded = template.replace(/{{date}}/g, now.toISOString().split("T")[0]).replace(/{{time}}/g, now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })).replace(/{{datetime}}/g, now.toLocaleString()).replace(/{{timestamp}}/g, now.getTime().toString()).replace(/{{year}}/g, now.getFullYear().toString()).replace(/{{month}}/g, (now.getMonth() + 1).toString().padStart(2, "0")).replace(/{{day}}/g, now.getDate().toString().padStart(2, "0"));
    return expanded;
  }
  createSnippetExtension() {
    const plugin = this;
    return import_view.EditorView.domEventHandlers({
      keydown(event, view) {
        if (event.key === " ") {
          const selection = view.state.selection.main;
          const line = view.state.doc.lineAt(selection.head);
          const textBeforeCursor = line.text.slice(0, selection.head - line.from);
          for (const snippet of plugin.settings.snippets) {
            const trigger = plugin.settings.triggerKey + snippet.trigger;
            if (textBeforeCursor.endsWith(trigger)) {
              event.preventDefault();
              const from = selection.head - trigger.length;
              const to = selection.head;
              const expanded = plugin.expandSnippet(snippet.template);
              view.dispatch({
                changes: { from, to, insert: expanded }
              });
              new import_obsidian.Notice(`\u2728 Expanded: ${snippet.trigger}`);
              return true;
            }
          }
        }
        return false;
      }
    });
  }
};
var SmartSnippetsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smart Snippets Settings" });
    new import_obsidian.Setting(containerEl).setName("Trigger character").setDesc("Character to start snippet triggers (default: /)").addText((text) => text.setPlaceholder("/").setValue(this.plugin.settings.triggerKey).onChange(async (value) => {
      this.plugin.settings.triggerKey = value || "/";
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Available Variables" });
    const variablesDiv = containerEl.createDiv({ cls: "snippet-variables" });
    variablesDiv.innerHTML = `
			<p>Use these variables in your templates:</p>
			<ul>
				<li><code>{{date}}</code> - Current date (YYYY-MM-DD)</li>
				<li><code>{{time}}</code> - Current time (HH:MM AM/PM)</li>
				<li><code>{{datetime}}</code> - Full date and time</li>
				<li><code>{{timestamp}}</code> - Unix timestamp</li>
				<li><code>{{year}}</code> - Current year</li>
				<li><code>{{month}}</code> - Current month (01-12)</li>
				<li><code>{{day}}</code> - Current day (01-31)</li>
			</ul>
		`;
    containerEl.createEl("h3", { text: "Built-in Snippets" });
    containerEl.createEl("p", {
      text: "These snippets are included by default. You can modify or delete them.",
      cls: "setting-item-description"
    });
    this.plugin.settings.snippets.forEach((snippet, index) => {
      const snippetContainer = containerEl.createDiv({ cls: "snippet-item" });
      snippetContainer.style.border = "1px solid var(--background-modifier-border)";
      snippetContainer.style.padding = "15px";
      snippetContainer.style.marginBottom = "15px";
      snippetContainer.style.borderRadius = "5px";
      snippetContainer.style.backgroundColor = "var(--background-secondary)";
      new import_obsidian.Setting(snippetContainer).setName(`${this.plugin.settings.triggerKey}${snippet.trigger}`).setDesc(snippet.description).addButton((button) => button.setButtonText("Delete").setWarning().onClick(async () => {
        this.plugin.settings.snippets.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
      new import_obsidian.Setting(snippetContainer).setName("Trigger").setDesc("The shortcut to type (without the trigger character)").addText((text) => text.setPlaceholder("trigger").setValue(snippet.trigger).onChange(async (value) => {
        this.plugin.settings.snippets[index].trigger = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(snippetContainer).setName("Description").setDesc("What this snippet does").addText((text) => text.setPlaceholder("Description").setValue(snippet.description).onChange(async (value) => {
        this.plugin.settings.snippets[index].description = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(snippetContainer).setName("Template").setDesc("The text that will be inserted").addTextArea((text) => {
        text.setPlaceholder("Template text...").setValue(snippet.template).onChange(async (value) => {
          this.plugin.settings.snippets[index].template = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.rows = 8;
        text.inputEl.style.width = "100%";
        text.inputEl.style.fontFamily = "monospace";
        return text;
      });
    });
    containerEl.createEl("h3", { text: "Add New Snippet" });
    let newTrigger = "";
    let newDescription = "";
    let newTemplate = "";
    new import_obsidian.Setting(containerEl).setName("New trigger").setDesc('Shortcut to type (e.g., "quote", "link", "header")').addText((text) => text.setPlaceholder("trigger").onChange((value) => {
      newTrigger = value;
    }));
    new import_obsidian.Setting(containerEl).setName("New description").setDesc("What this snippet does").addText((text) => text.setPlaceholder("Description").onChange((value) => {
      newDescription = value;
    }));
    new import_obsidian.Setting(containerEl).setName("New template").setDesc("The text that will be inserted").addTextArea((text) => {
      text.setPlaceholder("Template text...\nUse {{date}}, {{time}}, etc.").onChange((value) => {
        newTemplate = value;
      });
      text.inputEl.rows = 8;
      text.inputEl.style.width = "100%";
      text.inputEl.style.fontFamily = "monospace";
      return text;
    });
    new import_obsidian.Setting(containerEl).addButton((button) => button.setButtonText("Add Snippet").setCta().onClick(async () => {
      if (newTrigger && newTemplate) {
        this.plugin.settings.snippets.push({
          trigger: newTrigger,
          description: newDescription || "Custom snippet",
          template: newTemplate
        });
        await this.plugin.saveSettings();
        new import_obsidian.Notice("\u2705 Snippet added!");
        this.display();
      } else {
        new import_obsidian.Notice("\u274C Please fill in at least trigger and template");
      }
    }));
    containerEl.createEl("h3", { text: "How to Use" });
    const instructions = containerEl.createEl("div", { cls: "snippet-instructions" });
    instructions.innerHTML = `
			<p><strong>Using Snippets:</strong></p>
			<ol>
				<li>Type the trigger character (default: <code>/</code>)</li>
				<li>Type the snippet name (e.g., <code>meeting</code>)</li>
				<li>Press <strong>Space</strong></li>
				<li>The snippet expands into the template!</li>
			</ol>
			<p><strong>Example:</strong></p>
			<p>Type <code>/meeting</code> and press Space \u2192 Full meeting template appears!</p>
			<p><strong>Tips:</strong></p>
			<ul>
				<li>Use variables like {{date}} for dynamic content</li>
				<li>Create snippets for frequently used formats</li>
				<li>Combine with templates for powerful workflows</li>
			</ul>
		`;
  }
};
